### ISSUE TITLE
Figmaでプロタイプを作る

### ISSUE THREAD

**Issue by junseinagao** [shunkat/lostLovers#4]
[Figma](https://www.figma.com/file/grUsNMr3ztKZlrXzNbvOaT/%E6%99%B4%E3%82%8C%E3%81%AE%E3%81%A1%E3%82%A2%E3%83%A1%E3%83%80%E3%82%B9?node-id=0%3A1)

**Comment by sei-994** [comment]
https://www.figma.com/file/puNTzgtMvqHcu2qh8rcDQw/seiji-hoshino?node-id=0%3A1
仮作成
